const express = require("express");
const { auth } = require("../middlewares/auth");
const { requireRole } = require("../middlewares/roles");
const admin = require("../controllers/admin");
const meetingLocations = require("../controllers/meetingLocations");
const featureRequests = require("../controllers/featureRequests");
const productReports = require("../controllers/productReports");

const router = express.Router();
router.use(auth, requireRole("admin", "moderator"));
router.get("/dashboard", admin.dashboard);
router.get("/products", admin.listProducts);
router.get("/users", admin.listUsers);
router.get("/submissions", admin.listSubmissions);
router.post("/submissions/:submissionId/review", admin.reviewSubmission);
router.get("/settings", requireRole("admin"), admin.getSettings);
router.put("/settings", requireRole("admin"), admin.updateSettings);
router.patch("/users/:userId/status", requireRole("admin"), admin.updateUserStatus);
router.get("/content-reports", admin.listContentReports);
router.post("/content-reports/:reportId/review", requireRole("admin"), admin.reviewContentReport);
router.get("/product-reports", productReports.listProductReports);
router.post("/product-reports/:reportId/review", requireRole("admin"), productReports.reviewProductReport);
router.get("/meeting-locations", meetingLocations.listLocations);
router.post("/meeting-locations", requireRole("admin"), meetingLocations.createLocation);
router.patch("/meeting-locations/:locationId", requireRole("admin"), meetingLocations.updateLocation);
router.delete("/meeting-locations/:locationId", requireRole("admin"), meetingLocations.deactivateLocation);
router.get("/feature-requests", featureRequests.listFeatureRequests);
module.exports = router;
