const mongoose=require("mongoose");

const userschema=new mongoose.Schema({
    firstname:{
        type:String,
        required:true,
        trim:true,
    },
    lastname:{
        type:String,
        required:true,
        trim:true,
    },
    email:{
        type:String,
        required:true,
        trim:true,
        unique:true,
        index:true,
    },
    hashedpassword:{
        type:String,
        required:true,
    },
    accounttype:{
        type:String,
        default:"User"
    },
    roles:{
        type:[{
            type:String,
            enum:["user","moderator","admin"]
        }],
        default:["user"]
    },
    accountStatus:{
        type:String,
        enum:["active","suspended","blocked"],
        default:"active"
    },
    roleVersion:{
        type:Number,
        default:1
    },
    forgotpasswordlink:{
        type:String,
        index:true,
        sparse:true,
    },
    forgotpasswordlinkexpires:{
        type:Date,
    },
    image:{
        type:String,
    },
    products:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Product",
    }],
    additionaldetails:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Profile",
    },
    ratingandreviews:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Ratingandreviews",
    }],
})

module.exports=mongoose.model("User",userschema);
